name: build-docker-image
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    env:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: docker login
        run: |
          echo $DOCKER_HUB_TOKEN > my_password.txt
          cat ~/my_password.txt | docker login --username sericwang --password-stdin
      - name: build image
        run: |
          docker image build -t sericwang/fastapi-demo:latest .
      - name: push image
        run: |
          docker image push sericwang/fastapi-demo:latest