name: demo
on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test-code:
    runs-on: ubuntu-22.04
    container: python:3.8-slim
    services: 
      mongo: 
        image: mongo:6.0.2
        env:
          MONGO_INITDB_ROOT_USERNAME: root 
          MONGO_INITDB_ROOT_PASSWORD: example
        ports: 
          - 27017:27017
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      # - name: setup py
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.8    
      - name: install requirements
        run: pip install -r requirements.txt
      # - name: create mongodb container
      #   run: |
      #     docker run -d -p 27017:27017 --name some-mongo \
      #       -e MONGO_INITDB_ROOT_USERNAME=root \
      #       -e MONGO_INITDB_ROOT_PASSWORD=example \
      #       mongo
      - name: run py test
        id: run-py-test
        run: pytest
